from collections.abc import Sequence
from typing import Protocol

from hi_ayu.storage.models import MessageQuery, StorageCapabilities, StoredMessage, StoredSession


class SessionStore(Protocol):
    async def create_session(self, session: StoredSession) -> None: ...

    async def get_session(self, session_id: str) -> StoredSession | None: ...

    async def list_sessions(self, limit: int = 50, offset: int = 0) -> Sequence[StoredSession]: ...

    async def update_session_title(self, session_id: str, title: str) -> None: ...

    async def delete_session(self, session_id: str) -> None: ...


class MessageStore(Protocol):
    async def append_message(self, message: StoredMessage) -> None: ...

    async def append_messages(self, messages: Sequence[StoredMessage]) -> None: ...

    async def get_message(self, message_id: str) -> StoredMessage | None: ...

    async def list_messages(self, query: MessageQuery) -> Sequence[StoredMessage]: ...

    async def delete_message(self, message_id: str) -> None: ...

    async def delete_messages_by_session(self, session_id: str) -> int: ...


class SearchStore(Protocol):
    async def index_message(self, message: StoredMessage) -> None: ...

    async def remove_message_index(self, message_id: str) -> None: ...

    async def search_bm25(self, text: str, session_id: str | None, limit: int = 20) -> Sequence[str]: ...

    async def search_vector(self, embedding: list[float], session_id: str | None, limit: int = 20) -> Sequence[str]: ...


class PersistenceBackend(SessionStore, MessageStore, SearchStore, Protocol):
    @property
    def capabilities(self) -> StorageCapabilities: ...

    async def setup(self) -> None: ...

    async def close(self) -> None: ...
